-- Template: new public table exposed via Supabase Data API
--
-- Use this only for tables that SHOULD be reachable via supabase-js / REST / GraphQL.
-- For server-only tables, prefer a private schema instead of public.
--
-- References:
-- - https://supabase.com/docs/guides/database/data-api
-- - https://supabase.com/docs/guides/api/securing-your-api
-- - https://supabase.com/docs/guides/database/postgres/row-level-security

create table public.your_table (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  created_at timestamptz not null default now()
);

-- 1. Enable RLS first.
alter table public.your_table enable row level security;

-- 2. Add least-privilege grants.
-- Adjust per real access model. Do not blindly grant anon.
grant select on table public.your_table to authenticated;
grant insert, update, delete on table public.your_table to authenticated;

-- Optional: only if a trusted backend service will use Data API / service key.
grant all on table public.your_table to service_role;

-- 3. If inserts happen through the Data API and the table uses identity/serial ids,
--    the sequence also needs privileges.
grant usage, select on sequence public.your_table_id_seq to authenticated;
grant usage, select on sequence public.your_table_id_seq to service_role;

-- 4. Policies.
create policy "authenticated users can read own rows"
  on public.your_table
  for select
  to authenticated
  using (user_id = auth.uid());

create policy "authenticated users can insert own rows"
  on public.your_table
  for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "authenticated users can update own rows"
  on public.your_table
  for update
  to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy "authenticated users can delete own rows"
  on public.your_table
  for delete
  to authenticated
  using (user_id = auth.uid());

-- Optional pattern for mixed global + user-owned data:
--
-- create policy "authenticated users can read own rows and globals"
--   on public.your_table
--   for select
--   to authenticated
--   using (user_id = auth.uid() or user_id is null);

-- For backend-only tables in public, DO NOT use this template.
-- Instead:
--   - skip Data API grants entirely
--   - or move the table to a private schema
