services:
  rezepti:
    build:
      context: .
      target: dev
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./public:/app/public

  rezepti-prod:
    image: dacown/rezepti:latest
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    profiles:
      - prod
